### PR TITLE
ESM Transition

### PR DESCRIPTION
**Pull request by moromis**
Transitions Clustergrammer to ESM from CommonJS

Adds Redux as state management

### CODE REVIEW

**Comment by moromis** [comment]
Whoops, meant to do this in my fork.

**Comment by cornhundred** [comment]
Hi @moromis, feel free to make a pull request if you would like.

**Comment by moromis** [comment]
@cornhundred I think this project should remain, as what I'm working on currently doesn't have CJS support, and only supports ESM. I think I can fix that in the future but I'll still probably only be making commits to the fork over at [GumusLab](https://github.com/GumusLab/clustergrammer) and not pulling them into this repo. It's extremely broad changes to the point that it's a rewrite at this point.

**Comment by cornhundred** [comment]
Hi @moromis, thanks for the clarification the and I'm glad you all are able to use and improve Clustergrammer-GL. I'm hoping that some of the improvements that you all are working on can be eventually brought back into to this package and ultimately benefit Clustergrammer2 . I'll email you about it :)

**Pull request closed without merging**
